### ISSUE TITLE
Update title and description

### ISSUE THREAD

**Issue by AlexChesters** [fmtvp/tal-page-strategies#2]
The title has "application" spelt wrong and the link 404s.

**Comment by jmalk** [comment]
@AlexChesters The title of what, and which link?

**Comment by AlexChesters** [comment]
Here @jmalk 
![screen shot 2016-02-16 at 11 47 32](https://cloud.githubusercontent.com/assets/10558792/13075440/1b8ce3ec-d4a3-11e5-90d4-d85902335645.png)

**Comment by AlexChesters** [comment]
You can see it here https://github.com/fmtvp/tal-page-strategies

**Comment by jmalk** [comment]
Oh, that's a nightmare.

**Comment by AlexChesters** [comment]
I'd change it myself but I don't have admin rights on the repo :-1:

**Comment by AlexChesters** [comment]
This has now been resolved
