### ISSUE TITLE
Remove this repo

### ISSUE THREAD

**Issue by lukejpreston** [fmtvp/tal-page-strategies#3]
the [project tal launcher](https://github.com/fmtvp/library-tal-launcher) no longer depends on this project. I think it should be removed as it adds confusion

**Comment by johnbeech** [comment]
I have no problem with this, should we set a deadline?

**Comment by subsidel** [comment]
See comment in https://github.com/fmtvp/library-tal-launcher/pull/56

**Comment by lukejpreston** [comment]
Pending @subsidel comment I propose a month? give people time to update to the latest version? i.e. 23rd March

**Comment by drpacman** [comment]
Please can we get together as a group and discuss

**Comment by dhurrell** [comment]
It does depend on this project now.
