### ISSUE TITLE
How can we play a video on HBB video object?

### ISSUE THREAD

**Issue by bakikocak** [fmtvp/tal-page-strategies#4]
I have seen the example that plays a sample video (simplevideocomponent). But I guess it is HTML5 player and what i want to do is to play a video in a HBB TV app using broadcastVideoObject object. Any ideas will be welcomed. Cheers.

<object id="broadcastVideoObject" type="video/broadcast" style="position: absolute; width: 0px; height: 0px;"></object>

**Comment by tsadler1988** [comment]
Hi Baki,

TAL provides an API for interacting with the broadcast, and supports HbbTV, Samsung Maple, and Samsung Tizen. See [Broadcast Source Playback in our documentation](http://fmtvp.github.io/tal/other/broadcast.html) for full information on this. To enable this for a device that supports the HbbTV broadcastVideoObject, you would need to to setup your [Device Configuration](http://fmtvp.github.io/tal/overview/device-configuration.html) with `"antie/devices/broadcastsource/hbbtvsource"` in the `"modifiers"` block, and a `"pageStrategy"` that includes the broadcastVideoObject and is suitable for your specific device (`"hbbtv"`, `"html5hbbtvhybrid"`, `"html5hbbtvhybridappshow"`, or `"htmlbroadcastvideo"`).

The [simplevideocomponent](https://github.com/fmtvp/talexample/blob/master/static/script/appui/components/simplevideocomponent.js) in [TAL Example](https://github.com/fmtvp/talexample/) actually uses [TAL's deprecated media player](http://fmtvp.github.io/tal/widgets/media-playback.html), which has a similar API to HTML5 but is actually an abstraction that can use HTML5, CEHTML, or Samsung Maple under the hood. For up to date information on IP playback in TAL, see [our documentation](http://fmtvp.github.io/tal/overview/new-media-playback.html).

As far as I'm aware, the broadcastVideoObject can only be used for interacting with the broadcast stream, and never for IP playback. If you're trying to play IP content on an older HbbTV device that doesn't support HTML5 media playback, TAL's CEHTML abstraction should work fine.

Hope this answers your question, but please feel free to reopen this or open a new issue if you have any further questions.

Thanks,

Tom
